config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :votes
  root 'events#new'

end

app/models/destination.rb
require 'net/http'
require 'uri'
require 'json'

class Destination < ActiveRecord::Base
  has_many :votes
  belongs_to :event

  def price_estimate
    uri = URI.parse('https://sandbox-api.uber.com/v1/estimates/price')
    parameters = {
      :server_token => ENV['UBER_SERVER_TOKEN'],
      :start_latitude => 20.7484586,
      :start_longitude => -156.4380881,
      :end_latitude => latitude,
      :end_longitude => longitude
    }
    uri.query = URI.encode_www_form( parameters )
    response = Net::HTTP.get( uri )
    JSON.parse(response)
  end

end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessor :place_ids
  has_many :destinations
  has_many :votes, :through => :destinations
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :destination
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Method called by any endpoint to render a JSON response using the
  # BaseSerializer construct.
  def render_json (args={})
    # http_status
    http_status = args[:http_status]
    if http_status.nil?
      http_status = :ok
    end

    # Set the HTTP status in the render hash (for Rails rendering) and in the meta hash (for the API client).
    render_hash = { status: http_status, scope: current_user }
    render_hash.merge!({ current_user_data: args[:current_user_data] })
    meta_hash = { http_status: Rack::Utils.status_code(http_status) }

    unless args[:object].nil?
      meta_hash.merge!(args[:meta]) if args[:meta]

      # Add the object and the meta hash to the render hash for serialization.
      render_hash.merge!({ json: args[:object], meta: meta_hash })
      args[:root] = 'data' # TODO: Ian, I assume this should be forced set elsewhere?
      render_hash.merge!({ root: args[:root] }) if args[:root]

      # There should be a serializer or an each_serializer, but not both.
      if !args[:serializer].nil?
        render_hash.merge!({ serializer: args[:serializer] })
      elsif !args[:each_serializer].nil?
        render_hash.merge!({ each_serializer: args[:each_serializer] })
      end
    else
      # The JSON is the just the meta hash. (This doesn't pass through a serializer.)
      if !args[:errors].nil?
        # Add errors to the meta hash.
        meta_hash.merge!({ errors: args[:errors] })
      end

      render_hash.merge!({ json: { meta: meta_hash } })
    end

    return render(render_hash)
  end

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
end

app/controllers/events_controller.rb
require 'twilio-ruby'
class EventsController < ApplicationController

  def show
    @event = Event.find(params[:id])
    respond_to do |format|
      format.html
      format.json {
        render json: @event, serializer: EventSerializer
      }
    end
  end

  def new
    @client = GooglePlaces::Client.new(ENV['API_KEY'])
    @places = @client.spots(20.7508119,-156.4401073, :types => ['restaurant','cafe','bars'])
    @event = Event.new()
  end

  def create
    @event = Event.new(event_params)
    @client = GooglePlaces::Client.new(ENV['API_KEY'])
    @event.save
    @event.place_ids.split(',').each do |place_id|
      place = @client.spot(place_id)
      @event.destinations.create(
        name: place.name,
        latitude: place.lat,
        longitude: place.lng,
        vicinity: place.vicinity,
        address1: nil,
        address2: nil,
        city: nil,
        state: nil,
        country: nil,
        postal: nil
      )
    end
    @twilio_client = Twilio::REST::Client.new
    @twilio_client.messages.create(
      from: '+18084950075',
      to: '+18082805484',
      body: "Hi. Ben sent you a Nightout request. Click here to Vote #{event_url(@event)}"
    )
    respond_to do |format|
      format.html { redirect_to event_path(@event), notice: 'Event created' }
      format.json {
        render json: @event, serializer: EventSerializer
      }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:name, :time, :deadline, :place_ids)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/votes_controller.rb
require 'twilio-ruby'
class VotesController < ApplicationController

  def create
    @destination = Destination.find(params[:destination_id])
    @vote = Vote.create(destination_id: @destination.id)
    @destination.update_attributes(vote_count: @destination.votes.count)
    @event = @destination.event
    if @event.votes.count >= 4
      @twilio_client = Twilio::REST::Client.new
      @twilio_client.messages.create(
        from: '+18084950075',
        to: '+18082805484',
        body: "Nice! We have decided to go to #{@event.destinations.order('vote_count DESC').first.name} Call an Uber here. #{event_url(@event)}"
      )
    end
    respond_to do |format|
      format.html { redirect_to event_path(@destination.event), notice: 'Thanks for your vote' }
      format.json {
        render json: @destination.event, serializer: EventSerializer
      }
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def vote_params
    params.require(:vote).permit(:user_id, :destination_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destination_helper.rb
module DestinationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/vote_helper.rb
module VoteHelper
end

app/views/events/new.html.erb
<div class="container">
  <div class="row">
    <%= form_for @event do |f| %>
      <div class="form-group">
        <%= f.text_field :name, placeholder:'Name', class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.text_field :time, placeholder:'Time', class:'form-control' %>
      </div>
      <div class="form-group">
        <%= f.text_field :deadline, placeholder:'Deadline', class:'form-control' %>
      </div>
      <div class="form-group place_group">
        <% @places.each do |place| %>
            <div id="<%= place.place_id %>" class='place'>
              <div class='add_place btn btn-success pull-right'>Add</div>
              <div class='place_title'><%= place.name %></div>
              <div class='place_address'><%= place.vicinity %></div>
            </div>
        <% end %>
      </div>
      <%= f.hidden_field :place_ids, value:'' %>
      <%= f.submit class:'btn btn-success', style:'width:100%'%>
    <% end %>
  </div>
</div>

<script type="text/javascript">
  $(".add_place").click(function(e) {
    if (this.innerHTML == 'Add') {
      $(this).addClass('active').addClass('btn-danger').removeClass('btn-primary');
      this.innerHTML = 'Remove';
    } else {
      $(this).removeClass('active').addClass('btn-primary').removeClass('btn-danger');
      this.innerHTML = 'Add';
    }
    var place_ids = []
    $('.place_group .active').each(function(i, obj) {
        place_ids.push(this.parentElement.id);
    });
    $('#event_place_ids').val(place_ids);
  });
</script>

app/views/events/show.html.erb
<div class="container">
  <div class="row">
    <p>
      <strong>Name:</strong>
      <%= @event.name %>
    </p>

    <p>
      <strong>Time:</strong>
      <%= @event.time %>
    </p>

    <p>
      <strong>Deadline:</strong>
      <%= @event.deadline %>
    </p>
    <% first = true %>
    <% @event.destinations.order('vote_count DESC').each do |place| %>
        <div class='place <%= "bg-yellow" if @event.votes.count >= 4 && first %>'>
          <div class='place_vote pull-right'>
            <% if @event.votes.count >= 4 %>
              <% if first %>
                Winner!
              <% end %>
              <div class='btn btn-default'>
                <%= place.votes.count %>
              </div>
            <% else %>
              Vote: <%= link_to place.votes.count, votes_path(destination_id: place.id), method: :post, class: 'btn btn-primary' %>
            <% end %>
          </div>
          <div class='place_title'><%= place.name %></div>
          <div class='place_address'><%= place.vicinity %></div>
        </div>
        <% if @event.votes.count >= 4 && first %>
          <% first = false %>
          <div>
            <% place.price_estimate['prices'].each do |price| %>
              <div class='price_estimate'>
                <div class='pull-right'>
                  <a class="btn btn-primary" href="uber://?client_id=<%= ENV['UBER_CLIENT_ID'] %>&action=setPickup&pickup=my_location&dropoff[latitude]=<%= place.latitude %>&dropoff[longitude]=<%= place.longitude %>&dropoff[nickname]=<%= place.name %>&dropoff[formatted_address]=<%= place.vicinity %>&product_id=<%= price['product_id'] %>">
                  <%= price['display_name'] %></a>
                </div>
                <div><%= price['estimate'] %></div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Nightout</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>